<style>
    .payment-div{float: left; padding: 75px 0px 0px 30px; }
    .payment-title{color: #ffd34e; text-transform: uppercase; text-align: left}
    .payment-icon li{float: left; margin-right: 10px;}
</style>

<div class="payment-div">
    <p class="payment-title">payment method</p>
    <ul class="payment-icon">
        <li><img src="<?php echo $this->getSkinUrl('images/paypal.jpg') ?>" width="50" height="30" alt ="paypal" /></li>
        <li><img src="<?php echo $this->getSkinUrl('images/master.jpg') ?>" width="50" height="30" alt ="master card" /></li>
        <li><img src="<?php echo $this->getSkinUrl('images/visa.jpg') ?>" width="50" height="30" alt ="visa card" /></li>
   <ul>
</div>